interface TailwindFontStyles {
  fontWeight: string[]
  fontFamily: string[]
  fontStyle: string[]
}

const tailwindFontStyles: TailwindFontStyles = {
  fontWeight: [
    'none',
    'pbx-font-thin',
    'pbx-font-extralight',
    'pbx-font-light',
    'pbx-font-normal',
    'pbx-font-medium',
    'pbx-font-bold',
    'pbx-font-extrabold',
    'pbx-font-black',
  ],
  fontFamily: [
    'none',
    'pbx-font-sans',
    'pbx-font-serif',
    'pbx-font-mono',
    'pbx-font-arial',
    'pbx-font-helvetica',
    'pbx-font-georgia',
    'pbx-font-times',
    'pbx-font-times-new-roman',
    'pbx-font-courier',
    'pbx-font-courier-new',
    'pbx-font-verdana',
    'pbx-font-tahoma',
    'pbx-font-trebuchet',
    'pbx-font-garamond',
    'pbx-font-palantino',
    'pbx-font-bookman',
    'pbx-font-comic-sans',
    'pbx-font-impact',
    'pbx-font-lucida',
    'pbx-font-lucida-console',
    'pbx-font-lucida-sans',
    'pbx-font-candara',
    'pbx-font-optima',
    'pbx-font-avenir',
    'pbx-font-futura',
    'pbx-font-calibri',
    'pbx-font-cambria',
    'pbx-font-didot',
    'pbx-font-franklin-gothic',
    'pbx-font-rockwell',
    'pbx-font-baskerville',
    'pbx-font-jost',
    'pbx-font-raleway',
    'pbx-font-inter',
    'pbx-font-roboto',
    'pbx-font-open-sans',
    'pbx-font-lato',
    'pbx-font-montserrat',
    'pbx-font-poppins',
    'pbx-font-nunito',
    'pbx-font-merriweather',
    'pbx-font-playfair-display',
    'pbx-font-source-sans-3',
    'pbx-font-noto-sans',
    'pbx-font-work-sans',
    'pbx-font-quicksand',
    'pbx-font-pt-serif',
    'pbx-font-crimson-text',
  ],
  fontStyle: ['none', 'pbx-italic', 'pbx-non-italic'],
}

export default tailwindFontStyles
