/** i18n keys for block picker hints — keyed by block title in component.ts */
export const BLOCK_DESCRIPTION_KEYS: Record<string, string> = {
  'Single Image': 'block.desc.single_image',
  'Two Vertical Images': 'block.desc.two_vertical_images',
  'Two Square Images': 'block.desc.two_square_images',
  'Three Square Images': 'block.desc.three_square_images',
  'Four Square Images': 'block.desc.four_square_images',
  'Six Square Images Grid': 'block.desc.six_square_images_grid',
  'Two Square Images With Text': 'block.desc.two_square_images_with_text',
  'Three Vertical Images': 'block.desc.three_vertical_images',
  'Four Square Images With Text': 'block.desc.four_square_images_with_text',
  'Three Square Images With Text': 'block.desc.three_square_images_with_text',
  'Stats Stepped': 'block.desc.stats_stepped',
  'Stats With Two Column': 'block.desc.stats_two_column',
  'Timeline Simple': 'block.desc.timeline_simple',
  'Show Single Product': 'block.desc.show_single_product',
  'Show Multiple Products': 'block.desc.show_multiple_products',
  'Simple Centered CTA': 'block.desc.simple_centered_cta',
  'Left Simple CTA': 'block.desc.left_simple_cta',
  'Image & Left CTA': 'block.desc.image_left_cta',
  'Cards Slider': 'block.desc.cards_slider',
  'Testimonials Slider': 'block.desc.testimonials_slider',
  'Image Slider': 'block.desc.image_slider',
  'Hero Centered': 'block.desc.hero_centered',
  'Hero With Image': 'block.desc.hero_with_image',
  'Features Three Column': 'block.desc.features_three_column',
  'How It Works': 'block.desc.how_it_works',
  'Logo Bar': 'block.desc.logo_bar',
  'Large Quote': 'block.desc.large_quote',
  'Pricing Three Tiers': 'block.desc.pricing_three_tiers',
  'Team Members': 'block.desc.team_members',
  FAQ: 'block.desc.faq',
  'Newsletter CTA': 'block.desc.newsletter_cta',
  'Hero Dark': 'block.desc.hero_dark',
  'Feature Spotlight': 'block.desc.feature_spotlight',
  'Dark Stats': 'block.desc.dark_stats',
  'Editorial Banner': 'block.desc.editorial_banner',
  'Large Testimonial': 'block.desc.large_testimonial',
  'Feature Cards Grid': 'block.desc.feature_cards_grid',
  'Image & Editorial Text': 'block.desc.image_editorial_text',
  'Profile Card': 'block.desc.profile_card',
  'Contact Minimal': 'block.desc.contact_minimal',
  'Editorial List': 'block.desc.editorial_list',
}

export function getBlockDescriptionKey(title: string): string | undefined {
  return BLOCK_DESCRIPTION_KEYS[title]
}
