<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    x="0px"
    y="0px"
    width="18px"
    height="18px"
    viewBox="0 0 18 18"
    aria-hidden="true"
    fill="none"
  >
    <line
      x1="5.75"
      y1="16.25"
      x2="6.75"
      y2="13.25"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
    />
    <line
      x1="12.25"
      y1="16.25"
      x2="11.25"
      y2="13.25"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
    />
    <rect
      x="1.75"
      y="2.75"
      width="14.5"
      height="10.5"
      rx="2"
      ry="2"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
    />
    <line
      x1="9"
      y1="2.75"
      x2="9"
      y2="1.5"
      stroke="currentColor"
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="1.5"
    />
  </svg>
</template>
